import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CoinTextService {
  public coinData: any;
  constructor() {
    this.coinData = {
      'BTC': 'Bitcoin is the first successful decentralized cryptocurrency based on peer-to-peer technology with no central bank or authority involved in the transaction and production of the Bitcoin currency.',
      'ETH': 'Ethereum is the second biggest cryptocurrency in the world by market cap and an open software platform based on blockchain technology that enables developers to build and deploy decentralized applications.',
      'BCH': 'Bitcoin Cash is peer-to-peer electronic cash for the Internet. The coin is hard forked of the original Bitcoin and is completely decentralized and requires no trusted third parties to operate.',
      'LTC': 'Litecoin is a peer-to-peer decentralized cryptocurrency based on blockchain technology. Litecoin is designed to make transactions faster and easier and it was created by Google employee and the Director of Engineering at Coinbase Charlie Lee.',
      'DASH': 'Dash is a cryptocurrency launched in January 2014 as Xcoin that focuses on privacy and anonymity. Dash protects your privacy by anonymizing transaction that you make over the network using its PrivateSend technology.',
      'XLM': 'Stellar is identified as a blockchain platform that connects banks, payment systems and people and is aiming to be an open financial system that gives people of all income levels access to low-cost financial services.',
      'ADA': 'Cardano is a decentralised public blockchain and cryptocurrency project that is developing a smart contract platform which seeks to deliver more advanced features than any protocol previously developed.',
      'TRX': 'Tron is a blockchain based technology which supports a distributed digital storage platform that acts as a free entertainment by allowing content creators to host their work and grants the authorized user direct access to the entertainment content without intermediaries.',
      'IOTA': 'IOTA is a blockchain project that acts as a distributed ledger for the Internet of Things. The first ledger with microtransactions without fees as well as secure data transfer.',
      'NEO': 'NEO uses a smart economy approach to implement its distributed network concept. Its main objective is to digitize assets using the decentralized network of blockchain technology and digital identity.',
      'XMR': 'Monero is a decentralized peer-to-peer cryptocurrency launched in April 2014 as a fork of Bytecoin. that offers high level of anonymity for users and their transactions.',
      'USDT': 'Tether is a cryptocurrency backed up by the same amount of traditional fiat currencies. Tether is meant to act as a blockchain replacement for the US dollar by maintaining 1-to-1 ratio to it.',
      'XEM': 'NEM is a peer-to-peer crypto platform able to process transactions more efficiently than other blockchain networks, and is designed to compete with online payment processors.',
      'VEN': 'VeChain is a blockchain-based platform that aims to improve the day-to-day business operations and real-time tracking of various business processes and products via a blockchain-powered cloud services.',
      'ETC': 'Ethereum Classic is a fork of Ethereum that occurred after the DAO hack. It is a blockchain-based, public-source distributed computing platform featuring smart contract functionality.',
      'BNB': 'Binance Coin is the token issued by the Binance exchange that fuels all activities on the platform . The Binance Coin is Ethereum-based, and follows the ERC20 standard.',
      'QTUM': 'Qtum is a decentralized and open-source smart contract platform that represents a symbiosis between ethereum\'s smart contract functionality and bitcoin\'s security to create a blockchain made ready for business.',
      'OMG': 'OmiseGO is a blockchain based decentralized banking getaway, using the open wallet structure to provide exchange and trade services to the unbanked.',
      'BCN': 'Bytecoin is a peer-to-peer cryptocurrency and a blockchain platform and it was the first coin to use strong encryption features that mask identity and transaction details on a blockchain.',
      'ZEC': 'ZCash is a cryptocurency that originated from the Zerocoin, dating back to the 1980s. It is a pioneer in the zero – knowledge based cryptography addressing privacy concerns by allowing the content of a transaction to remain anonymous despite the fact that the transaction itself was available to the public.',
      'ICX': 'ICON is a blockchain technology and network framework designed to allow independent blockchains to interact with each other. ICON is supported through a cryptocurrency token, called ICX.',
      'LSK': 'Lisk is a blockchain-based application platform. Lisk enables app developers to create, distribute and manage decentralized applications (dApps) on a JavaScript-based software development kit (SDK).',
      'ONT': 'Ontology Network is a public infrastructure blockchain project and distributed trust collaboration platform.',
      'AE': 'Aeternity is a scalable blockchain platform that enables high bandwidth transacting, purely-functional smart contracts, and decentralized oracles.',
      'BTG': 'Bitcoin Gold is a distributed digital currency. It is a hard fork of Bitcoin that occurred on October 24th, 2017 in order to restore the mining functionality with common Graphics Processing Units (GPU).',
      'ZRX': '0x is an open protocol that facilitates the decentralized exchange of Ethereum-based tokens and assets. Developers can use 0x to build their own custom exchange apps with a wide variety of user-facing applications.',
      'DCR': 'Decred is a completely autonomous, open-source, blockchain-based cryptocurrency. Decred employs both miners to create blocks and validators to validate them, creating a hybrid PoS/PoW ledger.',
      'BTM': 'Bytom is a blockchain based interactive protocol of multiple byte assets. Heterogeneous byte-assets (indigenous digital currency, digital assets) that operate in different forms on the Bytom Blockchain and atomic assets can be registered, exchanged, gambled and engaged in other more complicated and contract-based interoperations via Bytom.',
      'STEEM': 'Steem is a cryptocurrency supporting the Steemit network. Steemit is a blockchain-based rewards platform for publishers to monetize content and grow community.',
      'XVG': 'Verge is a cryptocurrency designed for everyday usage. It aims to fulfill its initial purpose of providing individuals and businesses with a fast, efficient and decentralized way of making direct transactions while maintaining privacy.',
      'NANO': 'Nano represents a low-latency blockchain based payment platform that requires minimal resources and it is ideal for peer-to-peer transactions.',
      'BTS': 'BitShares is a open-source software with the main feature of creating Decentralized Autonomous Companies where people can own shares in, via blockchain technology. Its aim is to provide a way for people to buy shares into companies and later receive profit from the same companies.',
      'SC': 'Sia is a proof of work blockchain and an actively developed decentralized storage platform. Users all over the world contribute disk storage from their computers to form a decentralized network.',
      'RHOC': 'RChain supports multiple blockchains both public and private, even on the same node. The main technology of RChain is the Rho Virtual Machine (RhoVM) Execution Environment.',
      'WAN': 'Wanchain is a blockchain built upon the strengths of the Ethereum Blockchain. It represents a distributed financial infrastructure based on the digital assets it aims to offer, the transactions, investments, loans, the exchange and multi-currency settlement systems.',
      'GNT': 'The Golem Network is a decentralized computation network. Using Golem, users can buy or sell computational power from other users in a peer to peer environment.',
      'PPT': 'Populous is a cryptocurrency and a blockchain based project that works as a peer-to-peer (P2P) invoice financing platform',
      'BTCP': 'Bitcoin Private is a low-fee, fast and private transaction network that combines the best from ZClassic and Bitcoin. The cryptocurrency has been developed in line with Satoshi Nakamoto’s original vision of a decentralized network',
      'BCD': 'Bitcoin Diamond is a fork of Bitcoin that aims to reduce the cost of transfer by adding the lightning network. By increasing the total amount of Bitcoin Diamond 10-fold from the original Bitcoin, from 21 million to 210 million they intend to lower the price and with that decrease the cost of participation.',
      'STRAT': 'Stratis is a Proof-of-Stake (POS) cryptocurrency with limited emission and low inflation. STRAT is trading on reputable cryptocurrency exchanges and is valued by investors worldwide.',
      'WAVES': 'Waves is a blockchain based platform for crowdfunding. Waves facilitates fundraising, crowdfunding and trading of financial instruments on the blockchain with reduced volatility.',
      'DOGE': 'Dogecoin is a decentralized virtual cryptocurrency which uses peer-to-peer technology to carry out its operations. Dogecoin is scrypt-based and enables fast payments to anyone, anywhere across the globe.',
      'WICC': 'WaykiChain is fully decentralized currency and blockchain technology focused on game and betting.',
      'WTC': 'Waltonchain is blockchain based business ecosystem created by the combination of RFID and the blockchain. Waltonchain is unique but based on the Ethereum’s smart contracts and DASH’s privacy technology, backed up with master nodes',
      'REP': 'Augur is built on the Ethereum blockchain and it is a decentralized, peer-to-peer oracle and prediction platform that is designed to help users create prediction on markets movements or the outcome of any future event',
      'DGB': 'DigiByte is decentralized cryptocurrency with a primary focus on security and speed. You can use DigiByte to move money over the internet instantly and at minimal or no fee cost.',
      'SNT': 'Status is a mini-OS to interface with the emerging Ethereum ÐApp ecosystem. Status is built on top of Ethereum service layers and protocols and it combines a messenger with a decentralized applications browser that will bridge the gap between ÐApp Developers and the Mass Market.',
      'AION': 'Aion network aims to provide a multi-tier blockchain system to improve the scalability, privacy and interoperability of the blockchain. The Aion Network is designed to support custom blockchain architectures while providing a mechanism for cross-chain interoperability.',
      'HSR': 'Hshare is a decentralized criptocurrency based on a dual network blockchain. The Hshare platform is comprised both of a blockchain-based network and a DAG-based network.',
      'BAT': 'Basic Attention Token is a blockchain project that radically improves the efficiency of digital advertising by creating a new token that can be exchanged between publishers, advertisers, and users.',
      'NAS': 'Nebulas is a cryptocurency and a decentralized incentive-based platform. It is self-evolving blockchain system and search engine with a decentralized platform',
      'LRC': 'Loopring is an open, multilateral token exchange protocol for decentralized exchange on the Ethereum mainnet but it’s generic design ensures it may be deployed on top of any public blockchain.',
      'KMD': 'The Komodo cryptocurrency is forked from Zcash and it focuses on providing anonymity through zero knowledge proofs and security through a novel Delayed Proof of Work (dPoW) protocol.',
      'LOOM': 'Loom Network is an Ethereum-based platform for large-scale online games and social apps. Loom Network\'s dappchains are full-featured blockchains that are built to run parallel to Ethereum Smart Contracts.',
      'GXS': 'GXChain is a blockchain project focused on building a data economy. The idea is to create real world business applications that will make use of the data exchange over their blockchain network by using their own GXShares token. The project uses the Delayed Proof of Stake algorithm.',
      'ELA': 'Elastos is a blockchain-powered operating system for the SmartWeb. ELA is the token of the Elastos blockchain. It can be used for trading, investing in digital assets and paying for blockchain processing fees.',
      'CNX': 'Cryptonex brings acquiring to the blockchain. It acts as a payment system that allows easy conversion between their supported cryptocurrencies. They also have payment cards that can be used in almost any country for fiat payments.',
      'MITH': 'The Mithril Network is a decentralized social media platform. It allows users to mine Mithril tokens through "Social Mining" that consists of each user\'s postings and interactions in the Mithril platform.',
      'SYS': 'SysCoin is a decentralized global network based on the proof of work consensus. SyS represents a cryptocurrency, an altcoin and Syscoin token used to trade on the online crypto market.',
      'FSN': 'FUSION is a crypto finance platform that integrates the values of multiple blockchain technologies. FUSION provides cross-organization, cross-datasource, cross-chain technologies and smart contracts.',
      'ETHOS': 'Ethos is a cryptocurrency and a people-powered, multi-asset wealth management solution that makes it easy and safe for users to interact with the new economy.',
      'QASH': 'Quoine Liquid is a blockchain based trading platform. Quoine Liquid is based on a preexisting QUOINE’s technologies such as Matching Engine, a Smart Order routing, and a currency conversion engine.',
      'VERI': 'Veritaseum is a smart contract-based wallet interface that allows anyone to create, enter and manage smart contracts without the need for any kind of intermediaries, middleman or centralized authority.',
      'KNC': 'Kyber Network is a decentralized exchange for digital assets. The KyberNetwork enables payment APIs that allow Ethereum account holders a chance to receive crypto token payments.',
      'CENNZ': 'Centrality is a blockchain platform that represents an ecosystem, decentralized and related to connect different applications which will use the Blockchain technology',
      'FUN': 'FunFair is an Ethereum-based casino that allows users to bet in a trustless and decentralized model, featuing 3D games that can be built in HTML5. FunFair offers cheap fees in terms of gas costs.',
      'NULS': 'Nuls is an open-source blockchain platform. Their goal is to create a community-driven development based on the consensus mechanism proof-of-credit and modular architecture.',
      'THETA': 'Theta is a blockchain based video streaming and delivery network. The Theta token functions as an incentive mechanism that encourages users to share their unused memory and bandwidth, serving as video caching and relay nodes for the network.',
      'SUB': 'Substratum is an open-source foundation for the decentralized web that operates on nodes which use cryptography to secure the data and deliver it worldwide. Substratum provides free and unrestricted access to content for a new Web 3.0.',
      'ETN': 'Electroneum is a cryptocurrency that aims at winning over the online and mobile gaming world. The currency is built on a Bitcoin inspired blockchain.',
      'DRGN': 'Dragonchain (DRGN) is a business platform, drafted by a team under Disney. It is a incubator, marketplace and blockchain that operates through the use of the cryptocurrency Dragons.',
      'SOC': 'The All Sports Platform focuses on the global online market and intends to build a network of predictive service system in the sports industry.',
      'MYB': 'MyBit is a Decentralized Asset Management Platform that uses blockchain technology and Ethereum smart contracts to create a new asset class for decentralized Energy and AI infastructure.',
      'KIN': 'Kin is a decentralized ecosystem composed of a group of digital services launched by Kik. The Kin token is an Ethereum-based cryptocurrency intended to be used for daily online activites.',
      'ENG': 'Enigma is a decentralized data marketplace that guarantees the privacy of their users\' shared data cryptographically.',
      'XZC': 'Zcoin is a decentralized cryptocurrency that is guaranteeing true financial anonymity for those using it to make transactions.',
      'RLC': 'RLC is an Ethereum-based token used in the iExec, a blockchain-based distributed cloud computing platform.',
      'DGD': 'Digix is a Decentralized Autonomous Organization gold-tracking asset, based on the Ethereum blockchain that has developed a system of proving asset existence and ownership on the distributed ledger',
      'CMT': 'CyberMiles is a blockchain project aimed to provide customized smart contract templates for the e-commerce industry',
      'ARDR': 'Ardor is a Blockchain-as-a-Service platform that allows users to create their own customized child chains. Ardor evolves from the NXT blockchain and offers many improvements over its predecessor.',
      'ARK': 'ARK is a blockchain project built as a derivative from Lisk, Crypti and BitShares that was designed for mass adoption by providing users, developers, and startups with innovative blockchain technologies',
      'ELF': 'Aelf is a project launched by the Aelf Innovation Alliance. It is a customizable operating system (OS) specifically for blockchains.',
      'DCN': 'Dentacoin aims to bring the blockchain to the Global Dental Industry.',
      'POLY': 'Polymath Network is a platform system that provides participants with the ability to launch financial products on the blockchain. They also aim to create a standard token protocol for these financial products.',
      'XRP': 'Ripple is a cryptocurrency that is evolved from Ripplepay. The unique thing about Ripple is the function of a real-time gross settlement system. This makes it an interesting technology for banks that are always looking for faster ways to do settlements.',
      'BTCD': 'Bitcoin Dark is a fork of Bitcoin that goes in a completely different direction than its parent project. Bitcoin Dark focuses on anonimity, privacy and decentralization. This technology will further be developed under the KMD platform.',
      'EOS': 'The EOS project is building a blockchain architecture that could enable vertical and horizontal scaling of decentralized applications with the potential of making them an integral part of already established business processes. The EOS software acts as a base layer foundation or an Operating System that comes with batteries included providing accounts, authentication, databases, scheduling and more.',
    };
  }

  getCoinType (coin: any) {
    return this.coinData[coin];
  }
}
